### ISSUE TITLE
Errno::EMSGSIZE raised intermittently

### ISSUE THREAD

**Issue by rsutphin** [cdd/rspec-multiprocess_runner#1]
Sometimes in a long-running suite, you'll get errors like this:

```
     Failure/Error: Unable to find matching line from backtrace
     Errno::EMSGSIZE:
       Message too long - send(2)
```
or
```
Errno::EMSGSIZE: Message too long - send(2)
/Users/rsutphin/collaborativedrug/git/vault/ruby/vendor/cache/rspec-multiprocess_runner-e51276df5666/lib/rspec/multiprocess_runner/worker.rb:240:in `send'
/Users/rsutphin/collaborativedrug/git/vault/ruby/vendor/cache/rspec-multiprocess_runner-e51276df5666/lib/rspec/multiprocess_runner/worker.rb:240:in `send_message'
/Users/rsutphin/collaborativedrug/git/vault/ruby/vendor/cache/rspec-multiprocess_runner-e51276df5666/lib/rspec/multiprocess_runner/worker.rb:198:in `send_message_to_coordinator'
/Users/rsutphin/collaborativedrug/git/vault/ruby/vendor/cache/rspec-multiprocess_runner-e51276df5666/lib/rspec/multiprocess_runner/worker.rb:169:in `report_example_result'
/Users/rsutphin/collaborativedrug/git/vault/ruby/vendor/cache/rspec-multiprocess_runner-e51276df5666/lib/rspec/multiprocess_runner/reporting_formatter.rb:72:in `report_example_result'
/Users/rsutphin/collaborativedrug/git/vault/ruby/vendor/cache/rspec-multiprocess_runner-e51276df5666/lib/rspec/multiprocess_runner/reporting_formatter.rb:50:in `example_failed'
[…]
```

The same section of code when run independently does not have this problem. The max length for the connection is set to 64k, which seems like it should be more than enough for the sorts of messages we're dealing with here. Plus the messages should be the same from run to run, so the error should be repeatable.

**Comment by rsutphin** [comment]
> The max length for the connection is set to 64k

No, it's not. I misremembered something: there's a max length provided to `recv`, but neither `send` nor `socketpair` have a max length. So it must be in the kernel or something. The `send` man page suggests it is IOV_MAX, but I can't find documentation on what the value of that is.

**Comment by rsutphin** [comment]
```
2.2.3 :001 > require 'etc'
 => true 
2.2.3 :002 > Etc.uname
 => {:sysname=>"Darwin", :nodename=>"marvin", :release=>"15.0.0", :version=>"Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64", :machine=>"x86_64"} 
2.2.3 :003 > Etc.sysconf(Etc::SC_IOV_MAX)
 => 1024 
```

So it's only 1k on OS X. Maybe datagrams are not the way to go.

**Comment by bbxiao1** [comment]
Is this mostly the Rspec output hitting that limit?

**Comment by rsutphin** [comment]
There are two kinds of messages that are sent from a worker to the coordinator. The messages are sent as JSON-serialized hashes.

* One that indicates an entire file is complete. Contains the status name and the file name.
* One that indicates an example is complete. This one contains more data, particularly for a failed spec — it has the status name, the example status (passed, failed, pending), the example description, and the details of the execution (i.e., the error & backtrace if it failed).

The second one could get over 1k sometimes, I suppose, but it's weird that it doesn't happen the same way each time. In any case, I'm going to switch to a stream socket (which cannot raise this error, since it is allowed to send a message over multiple packets). Since I'm already using JSON-serialized values, there isn't that much value in using datagrams anyway.
