### ISSUE TITLE
Disable autorun for RSpec::Core::Runner

### ISSUE THREAD

**Issue by kdole** [cdd/rspec-multiprocess_runner#11]
RSpec::Core::Runner creates an at_exit hook that calls `run(ARGV, $stderr, $stdout)`. For rspec-multiprocess_runner this results in an error message when the run completes. For example, `multirspec -w 1 spec/some_spec.rb` will result in `cannot load such file -- /some/path/1` and `multirspec --worker-count 1 spec/some_spec.rb` will result in `invalid option: --worker-count`

Looks like we just need to call RSpec::Core::Runner.disable_autorun!

**Comment by bbxiao1** [comment]
LGTM
