### ISSUE TITLE
Change timeout behavior to per-example instead of per-file

### ISSUE THREAD

**Issue by rsutphin** [cdd/rspec-multiprocess_runner#2]
The current timeout behavior is a max time allowed for any particular file — if the runner running a file does not report it as complete before the file timeout expires, the runner is killed.

The goal is to prevent a build from taking forever because one file gets hung up. But it is tricky to set the timeout correctly — individual files in a suite might take a wide range of times, from milliseconds up to 10 minutes or more.

A better solution might be to have a timeout for the amount of time any given _example_ can take. This could be much shorter.

**Comment by kdole** [comment]
Sounds good. I think we have some examples that take multiple (many?) seconds. In most cases this is because we've condensed a bunch of examples into one, which is obviously a testing anti-pattern but can make the suite a lot faster.

**Comment by rsutphin** [comment]
I left it out of the description somehow, but the thing that spurred me to write this was avoiding false positives when reaping apparently-hung files. If a runner is still returning completed examples, it's clearly not hung up, even if it takes more than 10 minutes (or whatever). The per-example timeout could still be pretty long — 30 seconds or a minute — and still be a win in terms of accurately and more quickly identifying runners that are actually stalled.
