### ISSUE TITLE
Do not return successful exit code when there are a lot of failures in the first run when logging failing files

### ISSUE THREAD

**Issue by bbxiao1** [cdd/rspec-multiprocess_runner#8]
To avoid a long re-run, failing files are only logged if failing examples are less than 10% of total examples. However, because the flag is set the run exits "successfully". This results in false positives.

**Comment by rsutphin** [comment]
I noted these in my (delayed) review of #7, but to summarize the things that apply here:

* Only logging failed files when there are a few (< 10%) is surprising behavior. If this has to be the responsibility of the runner, it should be a separate documented option, with the default being to log all the failing files all the time. (I'm thinking that it would be better separation for the controlling code to make a decision based on the number of logged files.)
* The exit status of the command should not change based on whether the log-failing-files option is provided. If the calling code wants to do something different when there are logged failures, that's up to the calling code. The exit statuses should be simple and clear — nonzero = failures.
